Milestone Three
codesalley/book-store pull request #3
Opened 2021-05-14 14:15 UTC by juxsalley

# Milestone Three 
- implement ``CREATE_BOOK`` and `` DELETE_BOOK`` functionality
- used ``useRef`` hook to handle user input field values, so values will still persist if a user mistakenly refresh the page

2021-05-14 16:11 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @juxsalley  :wave:

_So far, you've implemented most of the required features of this milestone. Your codebase is well-organized and your linters are reporting no errors. Your PR title and summary are also on point. :+1:_

__However, some changes are required before this milestone can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] I dropped some inline comments below. Make the changes as appropriate.



* * *
**Please make the required changes and submit another review request when you are done.**

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-05-14 16:11 UTC, teekaytech commented on src/containers/BookForm.js
> +
The BookForm Component should: 

- [x] Store the title and the category in the state. <a href="https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/StoreTitleAndCatInState.png">screenshot from pathwright</a>. You're instructed to use state, not ref. 
- [x] Implement <code>handleChange</code> and attaches it to input's and select's <code>onChange</code> event <a href="https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/HandleChange.png">screenshot from pathwright</a>
This should be similar to: 
```JavaScript
handleChange({ target: { name, value } }) {
  this.setState({
    [name]: value,
  })
}

```

2021-05-14 16:11 UTC, teekaytech commented on src/containers/BookForm.js
> +          <button disabled={submited} className="btn" type="submit">Add Book</button>
- [x] Please specify the `onChange` attribute for each of the input fields, using the `handleChange` function as the value.

2021-05-14 16:11 UTC, teekaytech commented on src/containers/BookForm.js
> +  };
The `handleSubmit` (addBook) function can be improved. Checking for the type of `onSubmit` might not be necessary and resetting the form fields can be better handled if the state is used. This can be similar to:
```JavaScript
handleSubmit(event) {
  event.preventDefault();

  this.props.createBook({
    id: generateID(),
    title: this.state.title,
    category: this.state.category
  });

  this.setState({
    title: '',
    category: 'Action'
  });
}

```

2021-05-14 20:59 UTC, uche-inyama requested changes
## Changes Required

It would be nice if you refactor handleChange method and the useState hook that initializes the book object.

I have left inline comments for reference.

#### That's it, make these updates then submit another form for a code review.

### Happy coding :slightly_smiling_face: 

####  ``` Uchechukwu Henry Inyama ```

2021-05-14 20:59 UTC, uche-inyama commented on src/containers/BookForm.js
> +  const [bookCategory, setCategory] = useState('');
refactor this line of code like so:
```
 const [bookAttr, setBookAttr] = useState({
    title: '',
    Author: '',
    Year: '',
    category: ''
  })
```

2021-05-14 20:59 UTC, uche-inyama commented on src/containers/BookForm.js
> +  };
Refactor handleChange like so:

```

  const handleChange = ({ target: { name, value } }) => {
    setBookAttr( prev => (
    { 
      ...prev,
      [name]: value
    }));
  };

```

2021-05-14 21:22 UTC, juxsalley commented on src/containers/BookForm.js
> +  };
thanks

2021-05-15 00:57 UTC, Forison approved these changes
## Status::Approved✔️ 

#### Good job on refactoring the code as requested, kindly go ahead and merge the branch and proceed to the next milestone

#### Happy coding

Addo Forison

2021-05-15 01:13 UTC, closed without merging